### ISSUE TITLE
Support reading the format that z3c.bcrypt produces?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.password#10]
Now that we have a bcrypt password manager (and maybe a KDF manager, see #9) it might be nice if we could read the format for those two managers that z3c.bcrypt produces (they have distinct prefixes, just different from the prefixes our existing bcrypt manager uses). (I'm not 100% sure that the KDF would be compatible, but bcrypt should be.)

That way z3c.bcrypt can eventually be phased out, reducing the amount of dependencies for people that want bcrypt/kdf passwords. (The cryptacular library it uses doesn't seem to be as maintained as the bcrypt library this package uses.)

**Comment by icemac** [comment]
Could be a nice idea but I personally do not use `z3c.bcrypt`.
I'd suggest to implement it when we find someone who could benefit from this support.

**Comment by jamadden** [comment]
I do use z3c.bcrypt and it would be nice to be able to reduce dependencies.
