### ISSUE TITLE
RTD needs to install this package

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.password#11]
The RTD site isn't building properly. I imagine that's because the checkbox for "install this package" isn't checked:
```
looking for now-outdated files... none found
pickling environment... /home/docs/checkouts/readthedocs.org/user_builds/zopepassword/checkouts/latest/docs/api.rst:8: WARNING: autodoc: failed to import module u'zope.password.interfaces'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopepassword/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named password.interfaces
```

Can the owner of the RTD project please check that box? (I'm going to guess that's @tseaver)

**Comment by tseaver** [comment]
I've updated the RTD project to install `zope.annotation`.  The API docs are now populated.

**Comment by jamadden** [comment]
> On Sep 22, 2017, at 12:53, Tres Seaver <notifications@github.com> wrote:
> 
> I've updated the RTD project to install zope.annotation. The API docs are now populated.
> 
> 

Thank you!
