### ISSUE TITLE
Document the length limit on bcrypt passwords

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.password#8]
The underlying bcrypt library only takes into account the first 72 digits of the password when creating the hash. They document this, but only on their PyPI page.  Should we mention this in our docstring too?

This turns out to be a good thing for reducing DDOS attacks. z3c.bcrypt does the same, albeit with a much larger limit (4096), citing https://www.djangoproject.com/weblog/2013/sep/15/security/

**Comment by icemac** [comment]
+1 for mentioning this limitation in our docstring with a reference to its source.
